### PR TITLE
Fix compatibility issues when PHNT_VERSION = PHNT_WINXP

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by rich-ayr** [comment]
This is already fixed upstream, see https://github.com/winsiderss/phnt/issues/44#issuecomment-2354344393.

**Comment by rahaftiya11** [comment]
1973

**Comment by rahaftiya11** [comment]
UQBCNgyxgr90wXDHJyIciMQdCa0B8A2glsJP7gidN49qu9IF

**Comment by rahaftiya11** [comment]
https://github.com/0xPolygonHermez/zkevm-node/commit/8335850137041b2eebf5503387b704a4aa833cf6#commitcomment-149147334

**Pull request closed without merging**
